# Generated by Django 3.2 on 2022-08-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20220821_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoppoint',
            name='point',
        ),
        migrations.AddField(
            model_name='stoppoint',
            name='lat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stoppoint',
            name='lng',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
