# Generated by Django 3.2 on 2022-08-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_auto_20220831_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fixed', models.BooleanField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('km_price', models.FloatField()),
                ('wait_price', models.FloatField()),
                ('tax_price', models.FloatField()),
                ('extra_price', models.FloatField()),
                ('company_per', models.SmallIntegerField()),
            ],
        ),
    ]
